import { PrismaClient } from '@prisma/client';
import { createHash } from 'crypto';

const prisma = new PrismaClient();

const seedOffers = [
  {
    title: 'Développeur React / TypeScript',
    company: 'TechForce Intérim',
    location: 'Paris (75)',
    description: 'Mission longue durée pour développeur React expérimenté. Vous intégrerez une équipe Agile pour développer des interfaces web modernes. Maîtrise de TypeScript, React, et des outils modernes (Vite, Next.js) requise.',
    requirements: 'React, TypeScript, Next.js, Git, REST API',
    salaryRange: '350-450€ / jour',
    contractType: 'Intérim',
    experience: '3 à 5 ans',
    qualification: 'Bac+3',
    jobUrl: 'https://francetravail.fr/offres/seed-001',
    source: 'seed',
  },
  {
    title: 'Développeur Node.js Back-end',
    company: 'Adecco Digital',
    location: 'Lyon (69)',
    description: 'Nous recherchons un développeur Node.js pour renforcer notre équipe back-end. Travail sur des APIs REST, microservices et bases de données PostgreSQL. Environnement Docker et CI/CD.',
    requirements: 'Node.js, Express, PostgreSQL, Docker, REST API',
    salaryRange: '320-420€ / jour',
    contractType: 'Intérim',
    experience: '2 à 3 ans',
    qualification: 'Bac+2',
    jobUrl: 'https://francetravail.fr/offres/seed-002',
    source: 'seed',
  },
  {
    title: 'Développeur Full Stack JavaScript',
    company: 'Manpower IT',
    location: 'Bordeaux (33)',
    description: 'Poste full stack pour projet e-commerce en forte croissance. Stack : React, Node.js, MongoDB. Vous serez responsable du front et du back. Équipe de 5 personnes, méthodologie Scrum.',
    requirements: 'React, Node.js, MongoDB, JavaScript, Scrum',
    salaryRange: '300-400€ / jour',
    contractType: 'Intérim',
    experience: '2 à 4 ans',
    qualification: 'Bac+3',
    jobUrl: 'https://francetravail.fr/offres/seed-003',
    source: 'seed',
  },
  {
    title: 'Développeur PHP Symfony',
    company: 'Page Personnel',
    location: 'Nantes (44)',
    description: 'Mission intérim 6 mois renouvelable. Développement et maintenance d\'applications web sous Symfony 6. Vous travaillerez sur une plateforme SaaS avec forte charge. Connaissance Doctrine et Twig appréciée.',
    requirements: 'PHP, Symfony, Doctrine, MySQL, Twig',
    salaryRange: '280-380€ / jour',
    contractType: 'Intérim',
    experience: '3 à 5 ans',
    qualification: 'Bac+3',
    jobUrl: 'https://francetravail.fr/offres/seed-004',
    source: 'seed',
  },
  {
    title: 'Développeur Python / Data',
    company: 'Hays Technology',
    location: 'Paris (75)',
    description: 'Développeur Python pour une mission data dans le secteur financier. Traitement de données volumineuses, scripts ETL, et dashboards analytiques. Maîtrise Pandas, NumPy, et SQL.',
    requirements: 'Python, Pandas, NumPy, SQL, ETL',
    salaryRange: '400-500€ / jour',
    contractType: 'Intérim',
    experience: '3 à 5 ans',
    qualification: 'Bac+4',
    jobUrl: 'https://francetravail.fr/offres/seed-005',
    source: 'seed',
  },
  {
    title: 'DevOps / SRE',
    company: 'Michael Page Technology',
    location: 'Sophia Antipolis (06)',
    description: 'Intégration dans une équipe SRE pour gérer l\'infrastructure cloud (AWS). Mise en place de pipelines CI/CD, monitoring, et automatisation. Kubernetes et Terraform obligatoires.',
    requirements: 'Kubernetes, Terraform, AWS, CI/CD, Docker',
    salaryRange: '450-600€ / jour',
    contractType: 'Intérim',
    experience: '4 à 6 ans',
    qualification: 'Bac+5',
    jobUrl: 'https://francetravail.fr/offres/seed-006',
    source: 'seed',
  },
  {
    title: 'Développeur Mobile React Native',
    company: 'Spring Professional',
    location: 'Lille (59)',
    description: 'Mission pour développeur React Native sur une application grand public (iOS / Android). Vous gérez des features de bout en bout. Redux, navigation et intégration API REST.',
    requirements: 'React Native, iOS, Android, Redux, REST API',
    salaryRange: '350-450€ / jour',
    contractType: 'Intérim',
    experience: '2 à 4 ans',
    qualification: 'Bac+3',
    jobUrl: 'https://francetravail.fr/offres/seed-007',
    source: 'seed',
  },
  {
    title: 'Lead Développeur Front-end React',
    company: 'Randstad Digital',
    location: 'Paris (75)',
    description: 'Lead front-end pour piloter une équipe de 4 développeurs. Architecture des composants, revues de code, et choix techniques. Expertise avancée React, TypeScript, et tests unitaires.',
    requirements: 'React, TypeScript, Jest, architecture front-end, leadership',
    salaryRange: '500-650€ / jour',
    contractType: 'Intérim',
    experience: '6 à 8 ans',
    qualification: 'Bac+5',
    jobUrl: 'https://francetravail.fr/offres/seed-008',
    source: 'seed',
  },
  {
    title: 'Développeur Java Spring Boot',
    company: 'Expectra',
    location: 'Toulouse (31)',
    description: 'Développement de microservices Java dans le domaine aéronautique. Spring Boot, JPA/Hibernate, et tests unitaires JUnit. Sécurité OAuth2 et documentation OpenAPI.',
    requirements: 'Java, Spring Boot, JPA, JUnit, Microservices',
    salaryRange: '350-450€ / jour',
    contractType: 'Intérim',
    experience: '3 à 5 ans',
    qualification: 'Bac+5',
    jobUrl: 'https://francetravail.fr/offres/seed-009',
    source: 'seed',
  },
  {
    title: 'Développeur Vue.js / Nuxt',
    company: 'Akkodis',
    location: 'Grenoble (38)',
    description: 'Intégration dans une startup SaaS pour développer des interfaces Vue.js. Nuxt 3, Pinia, et TypeScript. Bonne maîtrise du CSS (Tailwind) et de l\'accessibilité web.',
    requirements: 'Vue.js, Nuxt, TypeScript, Tailwind CSS, Pinia',
    salaryRange: '300-400€ / jour',
    contractType: 'Intérim',
    experience: '2 à 4 ans',
    qualification: 'Bac+3',
    jobUrl: 'https://francetravail.fr/offres/seed-010',
    source: 'seed',
  },
  {
    title: 'Développeur React Télétravail',
    company: 'Freelance.com',
    location: 'Remote / Télétravail',
    description: 'Mission 100% remote pour développeur React. Projet e-commerce international. TypeScript, React Query, Zustand, et Next.js. Bon niveau d\'anglais requis pour les daily meetings.',
    requirements: 'React, TypeScript, Next.js, React Query, Zustand, anglais',
    salaryRange: '400-500€ / jour',
    contractType: 'Intérim',
    experience: '3 à 5 ans',
    qualification: 'Bac+3',
    jobUrl: 'https://francetravail.fr/offres/seed-011',
    source: 'seed',
  },
  {
    title: 'Ingénieur Automatisation Playwright',
    company: 'Capgemini',
    location: 'Paris (75)',
    description: 'Mission en automatisation de tests avec Playwright. Vous écrirez et maintiendrez une suite de tests E2E complète. Bonne connaissance JavaScript/TypeScript et CI/CD (GitHub Actions).',
    requirements: 'Playwright, JavaScript, TypeScript, CI/CD, GitHub Actions',
    salaryRange: '380-480€ / jour',
    contractType: 'Intérim',
    experience: '2 à 4 ans',
    qualification: 'Bac+3',
    jobUrl: 'https://francetravail.fr/offres/seed-012',
    source: 'seed',
  },
  {
    title: 'Développeur Next.js / SEO',
    company: 'Altea IT',
    location: 'Marseille (13)',
    description: 'Développement Next.js avec fort enjeu SEO. Optimisations SSR/SSG, Core Web Vitals, et structured data. Intégration headless CMS (Strapi ou Contentful). Tailwind CSS.',
    requirements: 'Next.js, SEO, SSR, Tailwind CSS, Strapi',
    salaryRange: '320-420€ / jour',
    contractType: 'Intérim',
    experience: '2 à 3 ans',
    qualification: 'Bac+3',
    jobUrl: 'https://francetravail.fr/offres/seed-013',
    source: 'seed',
  },
  {
    title: 'Architecte Logiciel',
    company: 'Sopra Steria',
    location: 'Paris (75)',
    description: 'Architecte logiciel senior pour un projet de transformation digitale bancaire. Définition des patterns d\'architecture, rédaction des ADR, accompagnement des équipes. Maîtrise des patterns DDD et CQRS.',
    requirements: 'DDD, CQRS, microservices, API design, Java ou Node.js',
    salaryRange: '600-800€ / jour',
    contractType: 'Intérim',
    experience: '8 à 10 ans',
    qualification: 'Bac+5',
    jobUrl: 'https://francetravail.fr/offres/seed-014',
    source: 'seed',
  },
  {
    title: 'Développeur Angular',
    company: 'Atos',
    location: 'Nice (06)',
    description: 'Mission Angular pour application de gestion RH. Angular 17, NgRx, et Material Design. Intégration avec API Spring Boot. Bonne maîtrise du testing (Jasmine / Karma).',
    requirements: 'Angular, NgRx, TypeScript, Material Design, Jasmine',
    salaryRange: '300-380€ / jour',
    contractType: 'Intérim',
    experience: '2 à 4 ans',
    qualification: 'Bac+3',
    jobUrl: 'https://francetravail.fr/offres/seed-015',
    source: 'seed',
  },
  {
    title: 'Développeur React Native iOS/Android',
    company: 'SQLI',
    location: 'Strasbourg (67)',
    description: 'Développement application mobile santé. React Native avec Expo. Intégration avec des API REST sécurisées (JWT). Expérience avec les stores Apple et Google Play.',
    requirements: 'React Native, Expo, iOS, Android, REST API, JWT',
    salaryRange: '330-430€ / jour',
    contractType: 'Intérim',
    experience: '2 à 3 ans',
    qualification: 'Bac+3',
    jobUrl: 'https://francetravail.fr/offres/seed-016',
    source: 'seed',
  },
  {
    title: 'Data Engineer',
    company: 'Keyrus',
    location: 'Lyon (69)',
    description: 'Construction et maintenance de pipelines de données. dbt, Airflow, BigQuery ou Snowflake. Écriture de transformations SQL complexes et documentation technique.',
    requirements: 'dbt, Airflow, SQL, Python, BigQuery ou Snowflake',
    salaryRange: '400-520€ / jour',
    contractType: 'Intérim',
    experience: '3 à 5 ans',
    qualification: 'Bac+4',
    jobUrl: 'https://francetravail.fr/offres/seed-017',
    source: 'seed',
  },
  {
    title: 'Développeur Web Front / React Télétravail',
    company: 'ITG',
    location: 'Remote / Télétravail',
    description: 'Mission 100% télétravail pour start-up insurtech. React, TypeScript, et styled-components. Mise en place d\'un design system et collaboration étroite avec les designers (Figma).',
    requirements: 'React, TypeScript, styled-components, Figma, design system',
    salaryRange: '350-450€ / jour',
    contractType: 'Intérim',
    experience: '2 à 4 ans',
    qualification: 'Bac+3',
    jobUrl: 'https://francetravail.fr/offres/seed-018',
    source: 'seed',
  },
  {
    title: 'Ingénieur Cloud AWS',
    company: 'Accenture',
    location: 'Paris (75)',
    description: 'Migration vers AWS d\'une infrastructure on-premise. Déploiement d\'infrastructures via Terraform, gestion de ECS/EKS, et mise en place de la surveillance avec CloudWatch.',
    requirements: 'AWS, Terraform, ECS, EKS, CloudWatch, infrastructure',
    salaryRange: '500-650€ / jour',
    contractType: 'Intérim',
    experience: '4 à 6 ans',
    qualification: 'Bac+5',
    jobUrl: 'https://francetravail.fr/offres/seed-019',
    source: 'seed',
  },
  {
    title: 'Développeur GraphQL / Apollo',
    company: 'Zenika',
    location: 'Paris (75)',
    description: 'Développement d\'une API GraphQL avec Apollo Server. Résolution de requêtes complexes, gestion des subscriptions WebSocket, et optimisation des performances (DataLoader).',
    requirements: 'GraphQL, Apollo, Node.js, TypeScript, WebSocket',
    salaryRange: '380-480€ / jour',
    contractType: 'Intérim',
    experience: '2 à 4 ans',
    qualification: 'Bac+3',
    jobUrl: 'https://francetravail.fr/offres/seed-020',
    source: 'seed',
  },
];

async function main() {
  console.log('Seeding job offers...');

  let created = 0;
  let skipped = 0;

  for (const offer of seedOffers) {
    const externalKey = createHash('md5')
      .update(`${offer.jobUrl}|${offer.title}|${offer.company}`)
      .digest('hex');

    try {
      await prisma.jobOffer.upsert({
        where: { externalKey },
        update: { isActive: true },
        create: { ...offer, externalKey },
      });
      created++;
    } catch {
      skipped++;
    }
  }

  console.log(`Done: ${created} created, ${skipped} skipped.`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
